/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver */

#ifndef _Included_org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver
#define _Included_org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver_initialize
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver
 * Method:    carve
 * Signature: (Ljava/lang/String;Lorg/sleuthkit/datamodel/ReadContentInputStream;J)V
 */
JNIEXPORT void JNICALL Java_org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver_carve
  (JNIEnv *, jclass, jstring, jobject, jlong);

/*
 * Class:     org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver
 * Method:    finalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sleuthkit_autopsy_scalpel_jni_ScalpelCarver_finalize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
